version: 0.2

phases:
  install:
    commands:
      - git config --global url.https://github.com/.insteadOf ssh://git@github.com/
      - npm install
  build:
    commands:
      - npm run build
      #- npm test
artifacts:
  files:
    - "**/*"
  base-directory: "build"
